apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio-on-aks.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "factorio-on-aks.name" . }}
    helm.sh/chart: {{ include "factorio-on-aks.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.factorio.port }}
      targetPort: factorio
      protocol: UDP
      name: factorio
  selector:
    app.kubernetes.io/name: {{ include "factorio-on-aks.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
